### ISSUE TITLE
Statistics are broken when using PostgreSQL

### ISSUE THREAD

**Issue by der-michik** [c3bottles/c3bottles#97]
Since 731b4dd8703030d9bbb3c4a31cea, statistics are broken when PostgreSQL is used as database backend. When using SQLite, everything works.

```
Traceback (most recent call last):
  File "/c3bottles/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/c3bottles/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/c3bottles/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/c3bottles/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/c3bottles/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/c3bottles/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/c3bottles/c3bottles/views/statistics.py", line 16, in html
    stats=Statistics()
  File "/c3bottles/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/c3bottles/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/c3bottles/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/c3bottles/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/c3bottles/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/c3bottles/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/c3bottles/c3bottles/../templates/statistics.html", line 3, in top-level template code
    {% set title = _("Numbers") %}
  File "/c3bottles/c3bottles/../templates/layout.html", line 20, in top-level template code
    {% block replacement %}
  File "/c3bottles/c3bottles/../templates/layout.html", line 25, in block "replacement"
    {% block content %}{% endblock %}
  File "/c3bottles/c3bottles/../templates/statistics.html", line 8, in block "content"
    {% if stats.drop_point_count > 0 and stats.report_count > 0: %}
  File "/c3bottles/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/c3bottles/c3bottles/views/statistics.py", line 34, in drop_point_count
    return DropPoint.query.filter(or_(DropPoint.removed == None, ~DropPoint.removed)).count()
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3230, in count
    return self.from_self(col).scalar()
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2983, in scalar
    ret = self.one()
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2954, in one
    ret = self.one_or_none()
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
    ret = list(self)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/c3bottles/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) argument of NOT must be type boolean, not type timestamp without time zone
LINE 4: WHERE drop_point.removed IS NULL OR NOT drop_point.removed) ...
                                                ^
 [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT drop_point.number AS drop_point_number, drop_point.time AS drop_point_time, drop_point.removed AS drop_point_removed, drop_point.type AS drop_point_type \nFROM drop_point \nWHERE drop_point.removed IS NULL OR NOT drop_point.removed) AS anon_1'] (Background on this error at: http://sqlalche.me/e/f405)
```

marudor?!

Why `or_(DropPoint.removed == None, ~DropPoint.removed)` instead of simply `DropPoint.removed == None`? Am I missing something?

**Comment by der-michik** [comment]
Fixed in the metrics branch, seems to work as intended.
